### ISSUE TITLE
Hex pathing slightly wonky

### ISSUE THREAD

**Issue by Battenhatch** [manuelVo/foundryvtt-drag-ruler#81] opened 2021-06-06 06:23 UTC
The pathing on hex grids is slightly wonky as seem here: https://youtu.be/XXiKPDkOtwc

No error warnings in the console.

Measuring is correct, it's only the path representation that is off.

**Comment by manuelVo** [comment] 2021-06-07 12:30
I've tracked this down to a bug in Foundry VTT itself and opened an issue about this in their bug tracker.
https://gitlab.com/foundrynet/foundryvtt/-/issues/5338

**Comment by patrickburk1988** [comment] 2021-08-03 07:40
@manuelVo: I dunno if looking through someone else's drag ruler implementation would help, but Will Saunder's [Show Drag Distance](https://github.com/wsaunders1014/ShowDragDistance) seems to have some sort of workaround for avoiding the wonkiness with hex grids.

**Comment by manuelVo** [comment] 2021-08-03 08:32
I was hoping for this core bug to be addressed in one of the 0.8 bug fix patches, but with 0.9 getting in shape that hope is quickly dwindling. Additionally I don't see this getting fixed for 0.9 either, so a workaround would probably be warranted. However my module development time is fairly limited right now and issues like the one at hand are a big pain to fix, so it would be great if everyone stumbling across this issue who's affected by this could give a thumbs up reaction to the initial post in this thread. That way I could gauge how many people are affected by this and if it's worth devoting my time to this issue at this point. Thanks!

**Comment by manuelVo** [comment] 2021-08-18 23:01
Apparently this bug will be solved in Foundry 9

**Comment by manuelVo** [comment] 2022-01-02 17:27
This bug is gone using Foundry v9.

**Comment by manuelVo** [comment] 2022-01-14 09:40
It appears this can still happen with Foundry v9. Enabling the Terrain Ruler module seems to cure this for some reason, however. So for anyone still experiencing this, a workaround would be to install and enable the Terrain Ruler module in your game.

**Comment by manuelVo** [comment] 2022-01-17 13:38
This is still caused by the same bug in core, which apparently isn't fully fixed yet. This is the new issue about this in their bug tracker: https://gitlab.com/foundrynet/foundryvtt/-/issues/6551

**Comment by manuelVo** [comment] 2022-10-14 14:38
Supposedly this bug is fixed now.

**Closed by manuelVo** 2022-10-14 14:38 UTC
Labels: FoundryVTT bug, confirmed
