### ISSUE TITLE
Shift-click on button breaks dragging token

### ISSUE THREAD

**Issue by SoldierC4** [manuelVo/foundryvtt-drag-ruler#191] opened 2022-04-11 23:37 UTC
FoundryVTT 9.266
System: pathfinder-2e 3.8.4
Modules: drag-ruler 1.12.8 and socketlib 1.0.10

Shift-clicking a roll button on a PF2E character sheet seems to break drag-ruler. After shift-clicking, dragging a token will always result in the token _not_ snapping to the grid (as if shift was held down). Tapping the shift button corrects the issue.

https://user-images.githubusercontent.com/7141086/162850045-533e54c3-3f35-411d-91f3-22ac9dfea37a.mp4

**Comment by manuelVo** [comment] 2022-04-12 05:51
This seems to be happening only with Pathfinder 2e - I cannot reproduce it in other game systems. Likely pathfinder 2e is suppressing the shift key up event in some way, so it doesn't reach Drag Ruler (which in turn will never notice that you've released the key).

**Comment by manuelVo** [comment] 2022-04-12 08:48
Yes. This is possible via Foundries "Configure Controls" settings menu.

**Comment by Last-Username** [comment] 2022-04-12 22:15
I'm experiencing this issue in 5e Foundry as well- shift click any button, and drag ruler detaches from the grid until shift is pressed again.

**Comment by manuelVo** [comment] 2022-04-15 07:18
I've tracked this down to a core bug: https://gitlab.com/foundrynet/foundryvtt/-/issues/6978

**Comment by manuelVo** [comment] 2022-10-13 06:10
The upstream issue was deleted, so I can no longer track this issue properly and since it's not a bug within Drag Ruler anyway I'm going to close this.

**Closed by manuelVo** 2022-10-13 06:10 UTC
Labels: FoundryVTT bug, confirmed

**Comment by SoldierC4** [comment] 2022-10-13 17:31
The upstream issue was migrated to github at https://github.com/foundryvtt/foundryvtt/issues/6978
But yes agree this ticket should be closed since it's not a DragRuler issue.
