### ISSUE TITLE
Feature Suggestion: Halve movement walking through creatures

### ISSUE THREAD

**Issue by GhostwheelX** [manuelVo/foundryvtt-drag-ruler#90] opened 2021-07-07 18:30 UTC
Might there be a way to add this as an option so that going through the square of creatures is considered "difficult terrain", and counts as double the movement required?

**Comment by manuelVo** [comment] 2021-07-07 19:08
This (and all other modes of diffiult terrain) are already supported. To get it working you need to install "Enhanced Terrain Layer" and "Terrain Ruler" alongside Drag Ruler and enable the appropriate setting in "Enhanced Terrain Layer" .

Duplicate of #89

**Closed by manuelVo** 2021-07-07 19:09 UTC
Labels: duplicate, question
