### ISSUE TITLE
Can't click on "Settings" with the module activated with Foundry 10.284

### ISSUE THREAD

**Issue by darvo90** [manuelVo/foundryvtt-drag-ruler#225] opened 2022-09-12 21:09 UTC
Hi,
Just to let you know, after updating to Foundry 10.284, the module (i tried disabling everything else and it's the only responsible) prevents me from clicking on the "Settings" button in the settings menu of the application.
Do you think is it possible to resolve?
Thank you so much!

**Comment by mistamichal** [comment] 2022-09-12 23:45
I can confirm the same behaviour for me, too, also with only this module active.

**Comment by jmcconn18** [comment] 2022-09-13 16:22
[Check out this issue here].(https://github.com/manuelVo/foundryvtt-drag-ruler/issues/221) Drag Ruler is currently not compatible with v10.

**Comment by darvo90** [comment] 2022-09-13 17:22
Thank you so much @jmcconn18!

**Comment by manuelVo** [comment] 2022-09-30 08:36
Can anyone confirm this is still happening with Foundry 10.286? I'm unable to reproduce this issue

**Comment by manuelVo** [comment] 2022-09-30 09:09
Stack trace on 10.286 according a report on discord:
```
Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
[No packages detected]
    at SchemaField._validateType (commons.js:4082:15)
    at SchemaField.validate (commons.js:3809:37)
    at Setting.validate (commons.js:5462:35)
    at new DataModel (commons.js:5239:26)
    at new Document (commons.js:5778:3)
    at new BaseSetting (commons.js:9789:3)
    at new ClientDocumentMixin (foundry.js:12941:5)
    at new Setting (foundry.js:21171:1)
    at ClientSettings.get (foundry.js:2768:19)
    at SettingsConfig._prepareCategoryData (foundry.js:71112:31)
    at SettingsConfig.getData (foundry.js:59172:23)
    at SettingsConfig._render (foundry.js:5067:29)
    at SettingsConfig._render (foundry.js:5780:17)
    at SettingsConfig._render (foundry.js:59241:18)
onError @ foundry.js:747
```

**Comment by manuelVo** [comment] 2022-09-30 10:15
According to Discord reports this happens in a fresh wfrp 4ed world with only Drag Ruler and socketlib in the Native App on Windows 11.

**Comment by marcoswalker** [comment] 2022-09-30 13:23
I got this error clicking on settings in Tagmar RPG system. Windows 10.

[127.0.0.1-1664544061701.log](https://github.com/manuelVo/foundryvtt-drag-ruler/files/9684505/127.0.0.1-1664544061701.log)

**Comment by manuelVo** [comment] 2022-09-30 15:45
The bug has been identified and will be fixed once Drag Ruler is updated for v10.

**Comment by Sinfulglare** [comment] 2022-10-01 17:36
> Can anyone confirm this is still happening with Foundry 10.286? I'm unable to reproduce this issue

Can confirm I get a critical error every time I run the mod. Even if I ignore the fact that it locks out configurable settings the mod just simply doesn't work at all right now.

**Comment by manuelVo** [comment] 2022-10-13 08:48
Drag Ruler v1.13.0 has just been released, which supports Foundry v10 and fixes this bug.

**Closed by manuelVo** 2022-10-13 08:48 UTC
