### ISSUE TITLE
Conflict with FoundryVTT Arms Reach

### ISSUE THREAD

**Issue by LordOHelmet** [manuelVo/foundryvtt-drag-ruler#106] opened 2021-08-22 21:25 UTC
### Environment Details
* Foundry VTT Version: 0.8.9
* Operating System: Windows
* How Are You Using Foundry: Froge with Chrome
* Which Game System: GURPS

### Issue Description

When both modules, Arms Reach and Drag Ruler are enabled Drag ruler doesn't show the distance any more.

**Comment by manuelVo** [comment] 2021-08-23 06:50
Duplicate of #105

**Closed by manuelVo** 2021-08-23 06:50 UTC
