### ISSUE TITLE
Support for PF1 metric system

### ISSUE THREAD

**Issue by SkavenKF** [manuelVo/foundryvtt-drag-ruler#25] opened 2021-02-17 19:59 UTC
If I use the metric system in PF1, everything is still displayed in feet and not in meters.

Thanks 😃

**Comment by manuelVo** [comment] 2021-02-17 21:03
Does the foundry builtin ruler measure in metric in your game?

**Comment by SkavenKF** [comment] 2021-02-17 23:17
Sorry, I expressed myself incorrectly 😕  . I did not originally mean the display of feet and meters (this is set in the scene), but the change of color in the metric system. See also: [PF1 - Fix metric speed display](https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/commit/9d8ca74775b9536e45af777f85f22c55ae3b4ae9)
![grafik](https://user-images.githubusercontent.com/10259801/108279295-ad299900-717c-11eb-9a83-6238efe252d6.png)
Until now i used "ShowDragDistance" with my Modification https://github.com/wsaunders1014/ShowDragDistance/issues/74

**Comment by manuelVo** [comment] 2021-02-18 00:46
What speed does the dragged character have, according to it's character sheet?

**Comment by SkavenKF** [comment] 2021-02-18 06:52
He has a speed of 9 (m). But you must enter 30 (feet), so the PF1 system converting (display) it automatically to 9. 
Drag Ruler use the Number 30 without converting it to metric [PF1 - Fix metric speed display](https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/commit/9d8ca74775b9536e45af777f85f22c55ae3b4ae9)


![grafik](https://user-images.githubusercontent.com/10259801/108316224-eb46ad00-71bc-11eb-874a-7de0f36b35f3.png) 
![grafik](https://user-images.githubusercontent.com/10259801/108316266-fac5f600-71bc-11eb-92b8-ab8dc7ceafd0.png)

**Comment by manuelVo** [comment] 2021-02-18 08:18
Please Check in your DragRuler settings which Speed Provder is selected.

If the selected Speed Provider is "System Pathfinder 1", this is a bug inside the Pathfinder game system (in this case Drag Ruler is asking the Pathfinder System "how far can this token move" and Pathfinder is responding with 30). In that case please file a bug in the [Pathfinder 1 repository](https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/issues).

**Comment by envy** [comment] 2021-04-02 14:10
The issue is, that the default sheet autoconverts feet to meters but ONLY for display purposes. It is still stored in feet and all the attributes still have it in feet. So you could say that it's a system bug that there is no way to get the converted speed.

Personally, I think it's wrong to autoconvert in the sheet and in my groups we just enter the value in meters (and change buffs like haste to apply the meter values). We also do not use the default sheet but another one that does not autoconvert so everything works fine for us.

**Comment by manuelVo** [comment] 2021-04-22 09:57
This issue has been addressed by the Pathfinder1 Speed Provider. ([PR that fixes this](https://gitlab.com/Furyspark/foundryvtt-pathfinder1/-/merge_requests/147))

**Closed by manuelVo** 2021-04-22 09:57 UTC
Labels: needs info
