### ISSUE TITLE
In V9 gets a periodic error

### ISSUE THREAD

**Issue by Zamrod** [manuelVo/foundryvtt-drag-ruler#135] opened 2021-12-14 16:47 UTC
Every once in a while when moving in V9, the token will stop mid way and give the following error:

Uncaught TypeError: Cannot read properties of null (reading 'width')
[No packages detected]
    at e.get (core.min.js:8)
    at LightSource._renderTexture (foundry.js:39315)
    at LightSource.drawMeshes (foundry.js:39677)
    at LightingLayer.refresh (foundry.js:28444)
    at PerceptionManager._update (foundry.js:32523)
    at foundry.js:32499

**Comment by manuelVo** [comment] 2021-12-29 22:16
I'm unable to reproduce this issue. Do you have any other modules enabled (and if so, does the error persist if only Drag Ruler and socketlib are enabled?)

**Comment by Zamrod** [comment] 2022-01-06 20:17
This is almost definitely related to #140

**Comment by manuelVo** [comment] 2022-01-23 16:47
#140 is fixed, so if they are related, this bug might likely be fixed as well. Since I was never able to reproduce it in the first place I'll close it for now. But should the issue still persist in Drag Ruler 1.10.2, feel free to reopen it.

**Closed by manuelVo** 2022-01-23 16:47 UTC
Labels: bug, needs info
